apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-app
    environment: testing
spec:
  containers:
  - name: test-container
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Hello from test pod!' && sleep 30; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: ENVIRONMENT
      value: "testing"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  restartPolicy: Always
  terminationGracePeriodSeconds: 30